version: "3.8"

services:
  db:
    image: postgres:15
    container_name: wikijs_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijsrocks
    volumes:
      - ./data/db:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:latest
    container_name: wikijs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    depends_on:
      - db
